### ISSUE TITLE
merge in node_exporter

### ISSUE THREAD

**Issue by finkr** [dlopes7/aix-prometheus-exporter#1]
Hello,

Good to see this project.

The official node exporter is actualy multi-platform.

Some examples for other OS:
* [uname_linux: Build for 32bit MIPS too](https://github.com/prometheus/node_exporter/pull/565)
* [Add cpu collector for darwin](https://github.com/prometheus/node_exporter/pull/391)

Franklin

**Comment by dlopes7** [comment]
Thanks @finkr I have a pull request opened there already

**Comment by finkr** [comment]
I didn't see that one !

https://github.com/prometheus/node_exporter/pull/1763

great !
